dist: bionic

language: nodejs
node_js:
  - 12

services:
  - docker

before_install:
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - echo $CI_COMMIT
  - docker build -t madebyais/hello-node:$CI_COMMIT .
  - docker images

install:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push madebyais/hello-node:$CI_COMMIT