dist: bionic

language: nodejs
node_js:
  - 12

services:
  - docker

before_install:
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - echo $CI_COMMIT
  - docker build -t madebyais/hello-node:$CI_COMMIT .
  - docker images
  - 'which ssh-agent || (sudo apt-get update -y && sudo apt-get install -y openssh-client)'
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push madebyais/hello-node:$CI_COMMIT
  - ssh $DEPLOYMENT_HOST "docker pull madebyais/hello-node:$CI_COMMIT"